services:
  - type: web
    name: child-ai-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn combined_api:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/.cache/huggingface
